### ISSUE TITLE
[META] Reconsider lunr.js as search engine

### ISSUE THREAD

**Issue by hidmic** [ros-infrastructure/rosindex#28]
Somewhat related to #19 and #20. Rosindex used to use [lunr.js](https://lunrjs.com/) as a small client-side search engine, relying on a pre-generated index in JSON format. At some point, it was replaced by a Google CSE because lunr.js would not scale (payload too big? search too expensive?). 

Now, lunr.js provides the ideal setup, as it doesn't pose any maintenance burden. But to make a call, first we need to:

- [ ] Try re-enabling lunr.js and assess its performance.
- [ ] Research on and assess payload optimizations (e.g. shards, deflation).
- [ ] Explore and assess alternatives (e.g. [Apache Solr](http://lucene.apache.org/solr/), [elasticlunr.js](http://elasticlunr.com/)).

**Comment by tfoote** [comment]
With #47 merged testing on github so far lunr seems to be working quite well locally or remotely. Clearly we're only running a subset of the ROS1 load, but the search content seems to be a significant subset of the load time. Here's a timing chart for a full reload.

![image](https://user-images.githubusercontent.com/447804/45911404-b190d280-bdc7-11e8-890c-eb3ddf52c79f.png)

I believe that this is approximately 400 packages across 2 distros at the moment. We talked about possibly splitting the search to be distro specific which could help keep things from blowing up too large and having a lot of duplicate content in the search results and in the indexes to search over. (Right now we see double of everything that's in both ardent and bouncy) 

![image](https://user-images.githubusercontent.com/447804/45911443-37ad1900-bdc8-11e8-9d26-7973c3fd3a34.png)

It looks like the biggest slowdown is that the search results are currently starting to load very late in the render cycle, and optimizing that would make more difference than optimizing the index size etc.

**Comment by tfoote** [comment]
With all of hydro through melodic ardent and bouncy it's 1 to 2 seconds and 2MB for the index

![image](https://user-images.githubusercontent.com/447804/46009215-b1b4fa80-c073-11e8-80b3-27e52646c79b.png)

This isn't horrible, but if we could split the search indexing into per distro and then it would probably be well under one second for all distros. And the delay before downloading it is also still a significant factor.

But it looks like lunr isn't unreasonable to keep using.

**Comment by hidmic** [comment]
@tfoote that's interesting. I would've expected lunr.js indexes to be way larger, but these remain rather small.

BTW I have not seen an obvious way to pull a multi part index into lunr.js, but we can definitely try using e.g. local storage to load early and reuse across page reloads. That might improve UX.

**Comment by hidmic** [comment]
We've settled with lunr.js, plus some sharding logic to boost load times. Closing this one.
